[theme]
base = "light"
backgroundColor = "#FBFBF9"
secondaryBackgroundColor = "#F5F5F3"
textColor = "#111111"
primaryColor = "#FF3B30"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
